<?php

$bcItems = array(
    array("name" => "Classes" , "url" => "/classes.html" )
);
?>

<?= $this->partial("partials/breadcrumb.phtml",array("items"=> $bcItems)) ?>


<div class="class-list">

    <h2>All Classes</h2>

    <ul>
    <?php foreach($classes as $className => $class){ ?>

        <li> <a href="<?= $this->url($class) ?>"><?= $className ?></a></li>

    <?php } ?>
    </ul>
    
</div>