<?php

    $items = array(
        array("name" => "Classes" , "url" => "/classes.html" ),
        $items[] = array("name" => $fullName)
    );

    $classDocblock =  $classDefinition->getParsedDocBlock();

?>

<?= $this->partial("partials/breadcrumb.phtml",array("items"=> $items)) ?>

<div class="class-header clearfix">


    <h1 class="class-name">
        <span class="class-type">Class</span>
        <strong>
            <?= $fullName ?>
        </strong>
    </h1>


    <div class="access-buttons">
        <a class="btn btn-default" href="<?= $this->url(Zephir\Documentation::sourceUrl($classDefinition)) ?>">Source</a>

        <?php if($this->themeOption("github")){ ?>
            <a class="btn btn-default" href="<?= $this->themeOption("github") . "/tree/master/" . $compilerFile->getFilePath() ?>">Github</a>
        <?php } ?>

        from namespace :
        <?php foreach($namespacePieces as $nsname => $nspath){ ?>
            <span class="namespace-piece">
                \ <a href="<?= $this->url(Zephir\Documentation::namespaceUrl($nspath)) ?>"><?=$nsname?></a>
            </span>
        <?php } ?>

    </div>

</div>

<?php if ($classDocblock) { ?>

    <?php if ($classDocblock->getSummary()) { ?>
        <h2 class="class-docblock-summary">
            <?= $classDocblock->getSummary() ?>
        </h2>
    <?php } ?>

    <?php if ($classDocblock->getDescription()) { ?>
        <div class="class-docblock-description code-inside"><?= $classDocblock->getDescription() ?></div>
    <?php } ?>
<?php } ?>


<div class="hidden-anchor"  id="methods"></div>
<div class="methods-summary standard-band">Methods</div>
<ul class="method-summary-list">
    <?php foreach($methods as $method){ ?>

        <?= $this->partial("partials/class/method-summary.phtml",array("method"=>$method)) ?>

    <?php } ?>
</ul>

<div class="hidden-anchor"  id="methods-details"></div>
<div class="methods-summary standard-band">Methods Details</div>
<ul class="method-details-list">
    <?php foreach($methods as $method){ ?>

        <?= $this->partial("partials/class/method-details.phtml",array("method"=>$method)) ?>

    <?php } ?>
</ul>