<html>


    <head>
        <link rel="stylesheet" type="text/css" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
        <link rel="stylesheet" type="text/css" href="https://static.phalconphp.com/www/css/phalcon.min.css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:700,400" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,700" rel="stylesheet" type="text/css">
        <link rel="stylesheet" type="text/css" href="<?= $this->asset("static/style.css") ?>" />
        <link rel="stylesheet" type="text/css" href="<?= $this->asset("static/prettify.css") ?>" />

        <link rel="shortcut icon" href="<?= $this->asset("static/favicon.ico") ?>">

        <script src="<?= $this->asset("static/jquery.min.js") ?>"></script>
        <script src="<?= $this->asset("static/prettify.js") ?>"></script>
        <script src="<?= $this->asset("api_definition.js") ?>"></script>

        <script>var ZepCurrentPath = '<?=$this->url("/")?>'</script>
        <script src="<?= $this->asset("static/script.js") ?>"></script>

        <?php if($this->themeOption("analytics")){ ?>

        <!-- Google Analytics -->
        <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', '<?= $this->themeOption("analytics") ?>', 'auto');
        ga('send', 'pageview');

        </script>
        <!-- End Google Analytics -->

        <?php } ?>

        <title><?= $this->getVar("title") ? $this->getVar("title") . " - " : "" ?>Phalcon API Documentation</title>

    </head>


    <body>
        <div id="header">
            <header class="page-header">
                <nav class="navbar" role="navigation">
                    <div class="container">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu-container">
                                <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand phalcon-logo" href="/"><span itemprop="name" class="sr-only">Phalcon PHP</span></a>
                        </div>

                        <div class="collapse navbar-collapse navbar-right" id="main-menu-container">
                            <ul class="nav navbar-nav main-menu">
                                <li class="first"><a href="//phalconphp.com/en/download" class="header-nav-link">Download</a></li>
                                <li><a href="//docs.phalconphp.com/en/latest/index.html" class="header-nav-link" target="_blank">Documentation</a></li>
                                <li><a href="//forum.phalconphp.com/" class="header-nav-link" target="_blank">Forum</a></li>
                                <li><a href="//blog.phalconphp.com/" class="header-nav-link" target="_blank">Blog</a></li>
                                <li><a href="//phalconist.com/" class="header-nav-link" target="_blank">Resources</a></li>
                                <li><a href="//phalconphp.com/en/about">About</a></li>
                                <li><div align="right">
                                        <iframe src="https://ghbtns.com/github-btn.html?user=phalcon&amp;repo=cphalcon&amp;type=watch&amp;count=true&amp;size=large" allowtransparency="true" frameborder="0" scrolling="0" width="152px" height="30px"></iframe>
                                    </div></li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>

            <div class="heading">
                <div class="container">
                    <div class="row">
                        <h2>API Documentation  <span class="version">v<?= $this->projectConfig("version") ?></span></h2>
                    </div>
                </div>
            </div>

        </div>

        <table>
            <tr>
                <td valign="top">
                    <div id="body-left">

                        <div class="header-search">
                            <input class="search-box" placeholder="Search for a class or namespace" type="text" />
                        </div>

                        <div id="menu-wrapper">
                        </div>
                    </div>
                </td>
                <td valign="top">

        <div id="body-right">
            <div class="content">
                <?= $this->partial($contentPartial) ?>
            </div>
        </div>
    </tr>
</table>

            <div class="prefooter">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-3 text-right">
                            <span>Follow along:</span>
                        </div>
                        <div class="col-sm-6 text-center">
                            <a href="https://twitter.com/phalconphp" alt="Twitter" class="btn-social btn-social-twitter"><i class="icon-twitter"></i></a>
                            <a href="https://www.facebook.com/pages/Phalcon-Framework/134230726685897" alt="Facebook" class="btn-social btn-social-facebook"><i class="icon-facebook"></i></a>
                            <a href="https://plus.google.com/102376109340560896457" alt="Google+" class="btn-social btn-social-googleplus"><i class="icon-googleplus"></i></a>
                            <a href="https://github.com/phalcon/cphalcon" alt="Github" class="btn-social btn-social-github"><i class="icon-github"></i></a>
                        </div>
                        <div class="col-sm-3">
                        </div>
                    </div>
                </div>

            </div>
            <footer class="footer">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-4 col-sm-3">
                            <h4>Download</h4>
                            <ul>
                                <li><a href="//phalconphp.com/download">Installing Phalcon</a></li>
                                <li><a href="//docs.phalconphp.com/en/latest/index.html" class="header-nav-link" target="_blank">Documentation</a></li>
                                <li><a href="//api.phalconphp.com">API</a></li>
                                <li><a href="//docs.phalconphp.com/en/latest/reference/tutorial.html">Tutorial</a></li>
                                <li><a href="//docs.phalconphp.com/en/latest/reference/tutorial.html#sample-applications">Sample Applications</a></li>
                            </ul>
                        </div>
                        <div class="col-xs-4 col-sm-3">
                            <h4>Community</h4>
                            <ul>
                                <li><a href="//forum.phalconphp.com/" class="header-nav-link" target="_blank">Forum</a></li>
                                <li><a href="https://github.com/phalcon/cphalcon">GitHub</a></li>
                                <li><a href="https://github.com/phalcon/cphalcon/issues">Issue Tracker</a></li>
                                <li><a href="http://stackoverflow.com/questions/tagged/phalcon">Stack Overflow</a></li>
                                <li><a href="//builtwith.phalconphp.com/">Built with Phalcon</a></li>
                                <li><a href="//store.phalconphp.com/">Store</a></li>
                            </ul>
                        </div>
                        <div class="col-xs-4 col-sm-2">
                            <h4>About</h4>
                            <ul>
                                <li><a class="link-black" href="//blog.phalconphp.com/">Blog</a></li>
                                <li><a href="//phalconphp.com/en/about">About</a></li>
                                <li><a href="//phalconphp.com/en/team">Team</a></li>
                                <li><a href="//phalconphp.com/en/roadmap">Roadmap</a></li>
                                <li><a href="//phalconphp.com/en/donate">Donate</a></li>
                                <li><a href="//phalconphp.com/en/consulting">Consulting</a></li>
                                <li><a href="//phalconphp.com/en/hosting">Hosting</a></li>
                            </ul>
                        </div>
                        <div id="license-spaccer" class="visible-xs"></div>
                        <div id="license-wrapper" class="col-xs-12 col-sm-4">
                            <p class="license">

                                Found a typo or an error? Want to improve this document? The documentation sources are available on <a href="https://github.com/phalcon/docs">Github</a><br>
                                Need support or have questions? Check our <a href="//forum.phalconphp.com">Forum</a><br>
                                <br>

                                Phalcon Framework is released under the <a href="https://github.com/phalcon/cphalcon/blob/master/docs/LICENSE.md">new BSD license</a>.<br>
                                Except where otherwise noted, content on this site is licensed under the
                                <a href="http://creativecommons.org/licenses/by/3.0/">Creative Commons Attribution 3.0 License.</a>

                            </p><div class="design">
                                <span>Designed by:</span>

                                <a href="http://www.fog-city.net/" class="fogcity" target="_blank" title="Fog City Software"><span>Fog City Software</span></a>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>

    </body>
</html>
