<html>


    <head>
        <link rel="stylesheet" type="text/css" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" />
        <link rel="stylesheet" type="text/css" href="https://static.phalconphp.com/css/phalcon.min.css" />
        <link href="//fonts.googleapis.com/css?family=Open+Sans:700,400" rel="stylesheet" type="text/css">
        <link href="//fonts.googleapis.com/css?family=Merriweather:400,700" rel="stylesheet" type="text/css">
        <link rel="stylesheet" type="text/css" href="<?= $this->asset("static/style.css") ?>" />

        <script src="<?= $this->asset("static/jquery.min.js") ?>"></script>
        <script src="<?= $this->asset("static/prettify.js") ?>"></script>
        <script src="<?= $this->asset("api_definition.js") ?>"></script>

        <script>var ZepCurrentPath = '<?=$this->url("/")?>'</script>
        <script src="<?= $this->asset("static/script.js") ?>"></script>

        <?php if($this->themeOption("analytics")){ ?>

        <!-- Google Analytics -->
        <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', '<?= $this->themeOption("analytics") ?>', 'auto');
        ga('send', 'pageview');

        </script>
        <!-- End Google Analytics -->

        <?php } ?>

        <title>Phalcon API Documentation</title>

    </head>


    <body onload="prettyPrint()">
        <div id="header">
            <header class="page-header">
                <nav class="navbar" role="navigation">
                    <div class="container">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu-container">
                                <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand phalcon-logo" href="/"><span itemprop="name" class="sr-only">Phalcon PHP</span></a>
                        </div>

                        <div class="collapse navbar-collapse navbar-right" id="main-menu-container">
                            <ul class="nav navbar-nav main-menu">
                                <li class="first"><a href="http://phalconphp.com/en/download" class="header-nav-link">Download</a></li>
                                <li><a href="//docs.phalconphp.com/en/latest/index.html" class="header-nav-link" target="_blank">Documentation</a></li>
                                <li><a href="//forum.phalconphp.com/" class="header-nav-link" target="_blank">Forum</a></li>
                                <li><a href="http://blog.phalconphp.com/" class="header-nav-link" target="_blank">Blog</a></li>
                                <li><a href="//phalconist.com/" class="header-nav-link" target="_blank">Resources</a></li>
                                <li><a href="//phalconphp.com/en/about">About</a></li>
                                <li><div align="right">
                                        <iframe src="//ghbtns.com/github-btn.html?user=phalcon&amp;repo=cphalcon&amp;type=watch&amp;count=true&amp;size=large" allowtransparency="true" frameborder="0" scrolling="0" width="152px" height="30px"></iframe>
                                    </div></li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>

            <div class="heading">
                <div class="container">
                    <div class="row">
                        <h2>API Documentation  <span class="version">v<?= $this->projectConfig("version") ?></span></h2>
                    </div>
                </div>
            </div>

        </div>




        <div id="body-left">

            <div class="header-search">
                <input class="search-box" placeholder="Search for a class or namespace " type="text" />
            </div>

            <div id="menu-wrapper">
            </div>



        </div>
        <div id="body-right">
            <div class="content">
                <?= $this->partial($contentPartial) ?>
            </div>
        </div>

    </body>



</html>
