<?php

    $items = array(
        array("name" => "Classes" , "url" => "/classes.html" ),
        $items[] = array("name" => $fullName , "url" => $this->url($classDefinition)),
        $items[] = array("name" => "Source"),
    );
?>

<?= $this->partial("partials/breadcrumb.phtml",array("items"=> $items)) ?>

<div class="class-header source clearfix">


    <h1 class="class-name">Source of <strong><?= $fullName ?></strong></h1>

    <div class="access-buttons">
        <a class="btn btn-default" href="<?= $this->url($classDefinition) ?>">Class Api</a>

        <?php if($this->themeOption("github")){ ?>
            <a class="btn btn-default" href="<?= $this->themeOption("github") . "/tree/master/" . $compilerFile->getFilePath() ?>">Github</a>
        <?php } ?>

        from namespace :
        <?php foreach($namespacePieces as $nsname => $nspath){ ?>
            <span class="namespace-piece">
                \ <a href="<?= $this->url(Zephir\Documentation::namespaceUrl($nspath)) ?>"><?=$nsname?></a>
            </span>
        <?php } ?>

    </div>

    
</div>


<pre class="zephir-source-file prettyprint linenums"><?= htmlentities(file_get_contents(realpath($compilerFile->getFilePath()))) ?></pre>